<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../AiRouter.AspNetCore/AiRouter.AspNetCore.csproj" />
    <ProjectReference Include="../AiRouter.Persistence.Sqlite/AiRouter.Persistence.Sqlite.csproj" />
    <ProjectReference Include="../AiRouter.Providers.OpenAI/AiRouter.Providers.OpenAI.csproj" />
  </ItemGroup>
</Project>
